/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AplicarVacinaController;
import controller.PacienteController;
import controller.ProfissionalController;
import controller.VacinaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.bean.AplicarVacinabean;
import model.bean.Pacientebean;
import model.bean.Profissionalbean;
import model.bean.Vacinabean;

/**
 *
 * @author artes
 */
public class AplicacaoVacinaView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AplicacaoVacinaView.class.getName());

    /**
     * Creates new form AplicacaoVacina
     */
    private AplicarVacinaController controller = new AplicarVacinaController();
    private boolean alterar = false;
    private int idAplicacao = 0;
    
    
    public AplicacaoVacinaView(AplicarVacinabean aplicarvacinabean) {
        initComponents();
        getListaPacientes();
        getListaProfissionais();
        getListaVacinas();
    }

    private void getListaPacientes(){
        PacienteController pacienteController = new PacienteController();
        
        for (Pacientebean p : pacienteController.read()) {
            cbPaciente.addItem(p);
        }
    }
    private void getListaProfissionais() {
    ProfissionalController profissionalController = new ProfissionalController();
    for (Profissionalbean b : profissionalController.read()) {
        cbProfissional.addItem(b);
    }
}
    private void getListaVacinas() {
    VacinaController vacinaController = new VacinaController();
    for (Vacinabean v : vacinaController.read()) {
        cbVacina.addItem(v);
    }
}
        
    private void limparCampos() {
        jLabelNomeProfissional.setText("");
        jFormattedTextFieldDataAplicacao.setText("");
        jTextFieldLocal.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        jLabelNomePaciente = new javax.swing.JLabel();
        jTextFieldLocal = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        jLabelDataAplicacao = new javax.swing.JLabel();
        btnAplicar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabelLocal = new javax.swing.JLabel();
        jLabelNomeProfissional = new javax.swing.JLabel();
        jFormattedTextFieldDataAplicacao = new javax.swing.JFormattedTextField();
        jLabelNomeVacina = new javax.swing.JLabel();
        cbProfissional = new javax.swing.JComboBox<>();
        cbPaciente = new javax.swing.JComboBox<>();
        cbVacina = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabelNomePaciente.setText("Nome do Paciente:");

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabelDataAplicacao.setText("Data da Aplicação:");

        btnAplicar.setText("Aplicar");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabelLocal.setText("Local:");

        jLabelNomeProfissional.setText("Nome do Profissional:");

        try {
            jFormattedTextFieldDataAplicacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataAplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataAplicacaoActionPerformed(evt);
            }
        });

        jLabelNomeVacina.setText("Nome da Vacina:");

        cbProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProfissionalActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabelDataAplicacao))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelLocal)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDataAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnAplicar)
                        .addGap(28, 28, 28)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(43, 43, 43)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabelNomePaciente)
                                .addGap(148, 148, 148)
                                .addComponent(jLabelNomeProfissional)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(cbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabelNomeVacina))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(cbVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(832, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeProfissional)
                    .addComponent(jLabelNomePaciente)
                    .addComponent(jLabelNomeVacina))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataAplicacao)
                    .addComponent(jFormattedTextFieldDataAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocal))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnImprimir)
                            .addComponent(btnCancelar)
                            .addComponent(btnExcluir)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAplicar)))
                .addGap(238, 238, 238))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        ConsultaAplicacaoView consultaaplicacaoView = new ConsultaAplicacaoView();
        consultaaplicacaoView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
  Pacientebean pacienteSelecionado = (Pacientebean) cbPaciente.getSelectedItem();
    Profissionalbean profissionalSelecionado = (Profissionalbean) cbProfissional.getSelectedItem();
    Vacinabean vacinaSelecionada = (Vacinabean) cbVacina.getSelectedItem();
    
    if (pacienteSelecionado == null || profissionalSelecionado == null || vacinaSelecionada == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione paciente, profissional e vacina.");
        return;
    }
    
    int idPaciente = pacienteSelecionado.getIdPaciente();
    int idProfissional = profissionalSelecionado.getIdProfissional();
    int idVacina = vacinaSelecionada.getIdVacina();
    String dataAplicacao = jFormattedTextFieldDataAplicacao.getText();
    String local = jTextFieldLocal.getText();

    AplicarVacinaController controller = new AplicarVacinaController();
    boolean sucesso = controller.create(idProfissional, idPaciente, idVacina, dataAplicacao, local);

    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Vacina aplicada com sucesso!");
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao aplicar vacina!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jFormattedTextFieldDataAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataAplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataAplicacaoActionPerformed

    private void cbProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProfissionalActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultaAplicacaoView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<Pacientebean> cbPaciente;
    private javax.swing.JComboBox<Profissionalbean> cbProfissional;
    private javax.swing.JComboBox<Vacinabean> cbVacina;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataAplicacao;
    private javax.swing.JLabel jLabelDataAplicacao;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelNomePaciente;
    private javax.swing.JLabel jLabelNomeProfissional;
    private javax.swing.JLabel jLabelNomeVacina;
    private javax.swing.JTextField jTextFieldLocal;
    // End of variables declaration//GEN-END:variables
}
